### PR TITLE
Version 2.0 rewrite

### PR DESCRIPTION
**Pull request by astra137**
I arbitrarily choose `1.0.0-rc` as a version, so that will probably need to be changed. I also arbitrarily changed to AVA for tests because it was familiar, even though Mocha supports testing promises too.

I also have half a mind to see functions accept objects instead of multiple arguments, which could allow certain calls to clean up rather nicely, ie. `const newSession = refresh(oldSession)` or `getUser(session)`.

I am still active on this, so I have no problem changing whatever needs to be changed.

### CODE REVIEW

**Comment by dscalzi** [comment]
If you're still interested, I would like to merge this and prepare for a 2.0 release on npm. I assume everything has been tested?

**Comment by astra137** [comment]
I bumped the project. Unit tests pass. I ran the two online-integration-ish tests and they passed.

One of the problems I'm thinking about is how to do online tests properly. I might make another package with a CLI for running this package's functions, or just waiting for issues to be submitted could also work.

**Comment by dscalzi** [comment]
Just let me know when this is ready to go - online testing is not a huge priority but if you can figure something out go for it.

**Comment by dscalzi** [comment]
I've put the current code (1.0) on a branch called legacy to prepare for this.

**Comment by astra137** [comment]
@dscalzi I think this is good enough, and further changes can go through a normal PR pattern in branches on this repo.

**Comment by dscalzi** [comment]
@maccelerated Merged/deployed to npm 👍

**Comment by jamen** [comment]
@maccelerated Would you mind taking ownership of this repo?  I sent a transfer request just now.  If not, I can just keep hanging onto it.

**Pull request merged**
